version: '3'
services:
    app:
        container_name: docker-node-mongo
        image: docker-node-mongo
        command: npm start
        restart: always
        build: .
        ports:
            - '4000:4000'
        links:
            - mongo
        environment: 
            - NODE_ENV=production
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'